/* NETVISION APP v2 */
'use strict';
const NV=window.NV={state:{view:'home',profiles:[],activeProfile:null,channels:[],filteredChannels:[],category:'Todos',channelIndex:-1,tvHls:null,mediaHls:null,currentMedia:null},
$:(s)=>document.querySelector(s),$$:(s)=>[...document.querySelectorAll(s)],esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm:v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),
show:s=>NV.$(s)?.classList.remove('hidden'),hide:s=>NV.$(s)?.classList.add('hidden'),toast:m=>{const t=NV.$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}};
function stop(v){if(!v)return;try{v.pause()}catch{};try{v.removeAttribute('src')}catch{};try{v.load()}catch{}}
NV.stopTV=()=>{if(NV.state.tvHls){try{NV.state.tvHls.destroy()}catch{}NV.state.tvHls=null}stop(NV.$('#tvVideo'))};
NV.stopMedia=()=>{if(NV.state.mediaHls){try{NV.state.mediaHls.destroy()}catch{}NV.state.mediaHls=null}stop(NV.$('#mediaVideo'));const f=NV.$('#mediaFrame');if(f)f.src='about:blank'};
NV.setView=view=>{if(NV.state.view==='tv'&&view!=='tv')NV.stopTV();if(NV.state.view==='media'&&view!=='media')NV.stopMedia();NV.state.view=view;NV.$$('.screen').forEach(x=>x.classList.add('hidden'));if(view==='home')NV.show('#homeScreen');if(view==='tv')NV.show('#tvScreen');if(view==='movies'||view==='series'){NV.show('#catalogScreen');window.NVCatalog?.load(view)}if(view==='media')NV.show('#mediaScreen');window.scrollTo({top:0,behavior:'instant'})};
NV.enter=i=>{const p=NV.state.profiles[i];if(!p)return;NV.state.activeProfile=p;localStorage.setItem('netvision_active_v7',p.id);NV.$('#profileGate').classList.add('hidden');NV.$('#app').classList.remove('hidden');NV.applyProfile?.(p)};
NV.loadProfiles=()=>{let a=[];try{a=JSON.parse(localStorage.getItem('netvision_profiles_v7')||'[]')}catch{};NV.state.profiles=Array.isArray(a)?a:[];NV.renderProfiles?.()};
function bind(){NV.$$('.home-card').forEach(b=>b.onclick=()=>NV.setView(b.dataset.view));NV.$('#homeBtn').onclick=()=>NV.setView('home');NV.$$('[data-home]').forEach(b=>b.onclick=()=>NV.setView('home'));NV.$('#settingsBtn').onclick=()=>NV.openProfile?.(NV.state.activeProfile?.id);NV.$('#profileBtn').onclick=()=>NV.openProfile?.(NV.state.activeProfile?.id);NV.$('#searchBtn').onclick=()=>NV.openSearch?.();window.addEventListener('keydown',e=>{if(NV.state.view!=='tv'||e.ctrlKey||e.metaKey||e.altKey||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();NV.changeChannel?.(-1)}if(e.key==='ArrowRight'){e.preventDefault();NV.changeChannel?.(1)}if(e.key==='Escape'&&document.fullscreenElement)document.exitFullscreen?.()})}
document.addEventListener('DOMContentLoaded',()=>{bind();NV.loadProfiles()});
